import dynamic from "next/dynamic";
import "./globals.css";

const ClientComponent =
  dynamic(() => import("@/components/ClientComponent"),
    { ssr: false });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body>
    <ClientComponent>
      {children}
    </ClientComponent>
    </body>
    </html>
  );
}
