# https://github.com/docker-library/docs/tree/master/postgres#how-to-use-this-image

version: '3.1'

services:

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 6677:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080