// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID          pgtype.UUID        `json:"id"`
	Body        string             `json:"body"`
	Creator     string             `json:"creator"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	CreatedTime pgtype.Timestamptz `json:"created_time"`
	UpdatedTime pgtype.Timestamptz `json:"updated_time"`
}

type Tag struct {
	Name string `json:"name"`
}

type Thread struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Creator     string             `json:"creator"`
	CreatedTime pgtype.Timestamptz `json:"created_time"`
	UpdatedTime pgtype.Timestamptz `json:"updated_time"`
	NumComments int32              `json:"num_comments"`
}

type ThreadTag struct {
	ThreadID pgtype.UUID `json:"thread_id"`
	TagName  string      `json:"tag_name"`
}

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
