basePath: /api/v1
definitions:
  user.AuthResponseJson:
    properties:
      token:
        type: string
      username:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: This is the backend API for the forum.
  license:
    name: All Rights Reserved.
  title: CVWO Forum Backend API
  version: "1.0"
paths:
  /user/create:
    post:
      consumes:
      - application/json
      description: Registers a new user with the given username and password
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.AuthResponseJson'
        "400":
          description: Username already exists
        "500":
          description: Internal Server Error
      summary: Handles registration requests
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: Logs in a user with the given username and password
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.AuthResponseJson'
        "400":
          description: Username does not exist
        "401":
          description: Incorrect password
        "500":
          description: Internal Server Error
      summary: Handles login requests
      tags:
      - user
securityDefinitions:
  Bearer:
    description: The word "Bearer", followed by a space, and then the JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
