// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID          pgtype.UUID
	Body        string
	Creator     string
	ThreadID    pgtype.UUID
	CreatedTime pgtype.Timestamptz
	UpdatedTime pgtype.Timestamptz
}

type Tag struct {
	Name string
}

type Thread struct {
	ID          pgtype.UUID
	Title       string
	Body        string
	Creator     string
	CreatedTime pgtype.Timestamptz
	UpdatedTime pgtype.Timestamptz
	NumComments int32
}

type ThreadTag struct {
	ThreadID pgtype.UUID
	TagName  string
}

type User struct {
	Username string
	Password string
}
